-- Phase 15 only: Owner reporting, complete paginated audit, prospective row evidence.
-- No backfill, transaction replay, opening balances or historical row changes.
BEGIN;
CREATE INDEX phase15_audit_time_idx ON public.erp_audit_records(occurred_at,id);
CREATE INDEX phase15_order_kind_time_idx ON public.orders(kind,status,completed_at,id);
REVOKE INSERT,UPDATE,DELETE,TRUNCATE ON public.audit_log FROM PUBLIC,anon,authenticated;
CREATE TRIGGER phase15_legacy_audit_immutable BEFORE UPDATE OR DELETE ON public.audit_log FOR EACH ROW EXECUTE FUNCTION public.reject_domain_history_rewrite();

CREATE FUNCTION public.capture_owner_domain_audit() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE before_value jsonb; after_value jsonb; row_value jsonb; entity uuid; ref text;
BEGIN
 IF TG_OP='UPDATE' AND NEW IS NOT DISTINCT FROM OLD THEN RETURN NEW; END IF;
 IF TG_TABLE_NAME='profiles' AND TG_OP='UPDATE' AND (to_jsonb(NEW)-'last_login')=(to_jsonb(OLD)-'last_login') THEN RETURN NEW; END IF;
 IF TG_OP<>'INSERT' THEN before_value:=to_jsonb(OLD); END IF;
 IF TG_OP<>'DELETE' THEN after_value:=to_jsonb(NEW); END IF;
 row_value:=coalesce(after_value,before_value);
 -- New financial revisions retain the previous actual version, not a fabricated
 -- overwritten row. Other inserts correctly have no previous value.
 IF TG_OP='INSERT' AND TG_NARGS=1 AND row_value ? 'revision' THEN
  EXECUTE format('SELECT to_jsonb(t) FROM public.%I t WHERE to_jsonb(t)->>%L=$1 AND revision<$2 ORDER BY revision DESC LIMIT 1',TG_TABLE_NAME,TG_ARGV[0]) INTO before_value USING row_value->>TG_ARGV[0],(row_value->>'revision')::integer;
 END IF;
 entity:=coalesce((row_value->>'id')::uuid,(row_value->>'user_id')::uuid,(row_value->>'order_item_id')::uuid,(row_value->>'receipt_id')::uuid,(row_value->>'thaan_id')::uuid,(row_value->>'finished_product_id')::uuid);
 ref:=coalesce(row_value->>'reference',row_value->>'reason',row_value->>'code');
 IF entity IS NULL THEN
  -- Composite permission keys have no domain UUID. A deterministic audit-only
  -- identity plus the actual key in reference preserves their identity.
  ref:=TG_TABLE_NAME||':'||jsonb_build_object('key',row_value->>'key','role_key',row_value->>'role_key','permission_key',row_value->>'permission_key')::text;
  entity:=md5(ref)::uuid;
 END IF;
 INSERT INTO public.erp_audit_records(actor_id,action,entity_table,entity_id,previous_value,new_value,reference,occurred_at)
 VALUES(auth.uid(),'row_'||lower(TG_OP),TG_TABLE_NAME,entity,before_value,after_value,coalesce(ref,TG_TABLE_NAME||':'||entity::text),clock_timestamp());
 IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END; $$;
DO $$ DECLARE t text; parent_key text; BEGIN
 FOREACH t IN ARRAY ARRAY['roles','permissions','fabrics','suppliers','receiving_batches','customers','sale_items','tailoring_job_lines','profiles','user_roles','user_permission_overrides','role_permissions','locations','barcodes','fabric_stock','thaans','thaan_costs','stock_movements','sales','tailoring_jobs','customer_tailoring_jobs','finished_product_receipts','finished_product_materials','materials','consumable_receipts','consumable_receipt_costs','inventory_movements','material_issues','material_issue_lines','stock_transfers','stock_transfer_lines','production_jobs','production_status_events','finished_products','orders','order_items','production_cost_lines','finished_product_cost_allocations','tailoring_factories','tailoring_sections','tailors','tailor_assignments','products','designs','tailoring_charges'] LOOP
  EXECUTE format('CREATE TRIGGER phase15_row_audit AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.capture_owner_domain_audit()',t);
 END LOOP;
 FOR t,parent_key IN SELECT * FROM(VALUES('fabric_stock_costs','fabric_stock_id'),('fabric_stock_prices','fabric_stock_id'),('finished_product_prices','finished_product_id'),('customer_tailoring_prices','job_id'),('tailoring_charge_versions','charge_id'),('design_charge_versions','design_id'),('production_cost_versions','production_job_id')) x LOOP
  EXECUTE format('CREATE TRIGGER phase15_row_audit AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.capture_owner_domain_audit(%L)',t,parent_key);
 END LOOP;
END; $$;
REVOKE ALL ON FUNCTION public.capture_owner_domain_audit() FROM PUBLIC,anon,authenticated;

CREATE FUNCTION public.owner_erp_report(p_dataset text,p_from timestamptz DEFAULT NULL,p_to timestamptz DEFAULT NULL,p_after text DEFAULT NULL,p_limit integer DEFAULT 100,p_search text DEFAULT NULL) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE source_sql text; rows_value jsonb; total_value bigint; last_key text; order_sql text; cursor_operator text; last_aggregate text; snapshot_dataset boolean;
BEGIN
 IF NOT public.has_role(auth.uid(),'owner') THEN RAISE EXCEPTION 'Owner required'; END IF;
 IF p_limit IS NULL OR p_limit NOT BETWEEN 1 AND 200 OR (p_from IS NOT NULL AND p_to IS NOT NULL AND p_from>=p_to) OR length(coalesce(p_after,''))>256 OR length(coalesce(p_search,''))>200 THEN RAISE EXCEPTION 'Valid half-open date range, cursor, search and 1–200 limit required'; END IF;
 CASE p_dataset
 WHEN 'stock' THEN source_sql:=$q$
 SELECT i.id::text||':'||l.id::text row_key,NULL::timestamptz event_at,jsonb_build_object('item_id',i.id,'kind',CASE WHEN i.thaan_id IS NOT NULL THEN 'fabric' WHEN i.material_id IS NOT NULL THEN 'consumable' ELSE 'finished_product' END,'item',coalesce(f.name,m.name,product.name),'batch',batch.code,'barcode',coalesce(fbc.code,pbc.code),'than_id',i.thaan_id,'piece_number',p.piece_number,'location',l.name,'location_id',l.id,'parent_id',l.parent_id,'location_active',l.active,'quantity',b.quantity::text,'unit',i.unit,'piece_status',p.status) data
 FROM public.v_inventory_location_balances b JOIN public.inventory_items i ON i.id=b.inventory_item_id JOIN public.locations l ON l.id=b.location_id LEFT JOIN public.thaans th ON th.id=i.thaan_id LEFT JOIN public.fabric_stock fs ON fs.id=th.fabric_stock_id LEFT JOIN public.fabrics f ON f.id=fs.fabric_id LEFT JOIN public.receiving_batches batch ON batch.id=fs.batch_id LEFT JOIN public.barcodes fbc ON fbc.id=fs.barcode_id LEFT JOIN public.materials m ON m.id=i.material_id LEFT JOIN public.finished_products p ON p.id=i.finished_product_id LEFT JOIN public.products product ON product.id=p.product_id LEFT JOIN public.barcodes pbc ON pbc.id=p.barcode_id
 $q$;
 WHEN 'fabric_stock' THEN source_sql:=$q$
 SELECT s.id::text row_key,s.created_at event_at,jsonb_build_object('id',s.id,'fabric',f.name,'batch',b.code,'barcode',bc.code,'entry_state',s.entry_state,'than_count',(SELECT count(*) FROM public.thaans WHERE fabric_stock_id=s.id),'unreconciled_thans',(SELECT count(*) FROM public.thaans th WHERE th.fabric_stock_id=s.id AND NOT EXISTS(SELECT 1 FROM public.inventory_items WHERE thaan_id=th.id)),'located_quantity_mm',(SELECT coalesce(sum(public.inventory_balance(i.id,NULL)),0)::text FROM public.inventory_items i JOIN public.thaans th ON th.id=i.thaan_id WHERE th.fabric_stock_id=s.id),'cp_paise_per_m',cp.cp_paise_per_m::text,'sp_paise_per_m',sp.sp_paise_per_m::text,'cp_version_id',cp.id,'sp_version_id',sp.id) data
 FROM public.fabric_stock s JOIN public.fabrics f ON f.id=s.fabric_id JOIN public.receiving_batches b ON b.id=s.batch_id JOIN public.barcodes bc ON bc.id=s.barcode_id LEFT JOIN LATERAL(SELECT * FROM public.fabric_stock_costs WHERE fabric_stock_id=s.id ORDER BY revision DESC LIMIT 1) cp ON true LEFT JOIN LATERAL(SELECT * FROM public.fabric_stock_prices WHERE fabric_stock_id=s.id ORDER BY revision DESC LIMIT 1) sp ON true
 $q$;
 WHEN 'batches' THEN source_sql:=$q$ SELECT b.id::text row_key,NULL::timestamptz event_at,to_jsonb(b)||jsonb_build_object('supplier',s.name,'fabric_stock_count',(SELECT count(*) FROM public.fabric_stock WHERE batch_id=b.id),'than_count',(SELECT count(*) FROM public.thaans WHERE batch_id=b.id)) data FROM public.receiving_batches b LEFT JOIN public.suppliers s ON s.id=b.supplier_id $q$;
 WHEN 'thans' THEN source_sql:=$q$
 SELECT th.id::text row_key,th.created_at event_at,jsonb_build_object('id',th.id,'fabric',f.name,'batch',b.code,'fabric_barcode',bc.code,'legacy_barcode',th.barcode,'status',th.status,'original_mm',th.original_mm::text,'located_quantity_mm',CASE WHEN i.id IS NOT NULL THEN public.inventory_balance(i.id,NULL)::text END,'reconciled',i.id IS NOT NULL,'fabric_stock_id',th.fabric_stock_id) data FROM public.thaans th LEFT JOIN public.inventory_items i ON i.thaan_id=th.id LEFT JOIN public.fabric_stock fs ON fs.id=th.fabric_stock_id LEFT JOIN public.barcodes bc ON bc.id=fs.barcode_id LEFT JOIN public.fabrics f ON f.id=th.fabric_id LEFT JOIN public.receiving_batches b ON b.id=th.batch_id
 $q$;
 WHEN 'consumables' THEN source_sql:=$q$ SELECT m.id::text row_key,NULL::timestamptz event_at,to_jsonb(m)-'qty_on_hand'||jsonb_build_object('legacy_quantity_snapshot',m.qty_on_hand::text,'located_quantity',CASE WHEN i.id IS NOT NULL THEN public.inventory_balance(i.id,NULL)::text END,'reconciled',i.id IS NOT NULL) data FROM public.materials m LEFT JOIN public.inventory_items i ON i.material_id=m.id $q$;
 WHEN 'consumable_receipts' THEN source_sql:=$q$ SELECT r.id::text row_key,r.received_at event_at,jsonb_build_object('id',r.id,'material',m.name,'location',l.name,'quantity',r.quantity::text,'unit',r.unit,'cp_paise_per_unit',c.cp_paise_per_unit::text,'actor_id',r.received_by,'received_at',r.received_at,'reason',r.reason) data FROM public.consumable_receipts r JOIN public.materials m ON m.id=r.material_id JOIN public.locations l ON l.id=r.destination_location_id LEFT JOIN public.consumable_receipt_costs c ON c.receipt_id=r.id $q$;
 WHEN 'customer_tailoring' THEN source_sql:=$q$
 SELECT j.id::text row_key,j.created_at event_at,to_jsonb(j)||jsonb_build_object('customer',c.name,'factory',f.name,'section',s.name,'tailor',t.real_name,'fabric_cp_total_paise',price.fabric_cp_total_paise::text,'tailoring_charge_paise',price.tailoring_charge_paise::text,'final_customer_price_paise',price.final_customer_price_paise::text) data FROM public.customer_tailoring_jobs j JOIN public.customers c ON c.id=j.customer_id JOIN public.tailor_assignments a ON a.id=j.tailor_assignment_id JOIN public.tailoring_factories f ON f.id=a.factory_id LEFT JOIN public.tailoring_sections s ON s.id=a.section_id JOIN public.tailors t ON t.id=a.tailor_id LEFT JOIN LATERAL(SELECT * FROM public.customer_tailoring_prices WHERE job_id=j.id ORDER BY revision DESC LIMIT 1) price ON true
 $q$;
 WHEN 'configuration' THEN source_sql:=$q$
 SELECT 'factory:'||id::text row_key,created_at event_at,to_jsonb(t)||jsonb_build_object('kind','factory') data FROM public.tailoring_factories t UNION ALL SELECT 'section:'||id::text,created_at,to_jsonb(t)||jsonb_build_object('kind','section') FROM public.tailoring_sections t UNION ALL SELECT 'tailor:'||id::text,created_at,to_jsonb(t)||jsonb_build_object('kind','tailor') FROM public.tailors t UNION ALL SELECT 'assignment:'||id::text,valid_from,to_jsonb(t)||jsonb_build_object('kind','assignment') FROM public.tailor_assignments t UNION ALL SELECT 'charge:'||id::text,NULL::timestamptz,to_jsonb(t)||jsonb_build_object('kind','tailoring_charge') FROM public.tailoring_charges t UNION ALL SELECT 'charge_version:'||id::text,recorded_at,to_jsonb(t)||jsonb_build_object('kind','tailoring_charge_version','amount_paise',amount_paise::text) FROM public.tailoring_charge_versions t UNION ALL SELECT 'design:'||id::text,NULL::timestamptz,to_jsonb(t)||jsonb_build_object('kind','design') FROM public.designs t UNION ALL SELECT 'design_version:'||id::text,recorded_at,to_jsonb(t)||jsonb_build_object('kind','design_charge_version','amount_paise',amount_paise::text) FROM public.design_charge_versions t UNION ALL SELECT 'product:'||id::text,NULL::timestamptz,to_jsonb(t)||jsonb_build_object('kind','product') FROM public.products t
 $q$;
 WHEN 'material_issues','tailor_usage' THEN source_sql:=$q$
 SELECT line.id::text row_key,mi.issued_at event_at,jsonb_build_object('id',line.id,'issue',mi.code,'issue_type',mi.issue_type,'job',coalesce(pj.code,cj.code),'job_kind',CASE WHEN pj.id IS NOT NULL THEN 'owner_production' ELSE 'customer_tailoring' END,'factory',f.name,'section',s.name,'tailor',t.real_name,'assignment_id',a.id,'source',loc.name,'item',coalesce(fabric.name,material.name),'fabric_stock_id',line.fabric_stock_id,'than_id',line.thaan_id,'material_id',line.material_id,'quantity_issued',line.quantity::text,'unit',line.unit,'actual_piece_usage',CASE WHEN pj.id IS NOT NULL THEN (SELECT coalesce(sum(quantity),0)::text FROM public.finished_product_materials WHERE material_issue_line_id=line.id) END,'actual_usage_scope',CASE WHEN pj.id IS NOT NULL THEN 'recorded_finished_piece_allocations' ELSE 'not_recorded_for_customer_tailoring' END,'actor_id',mi.issued_by,'issued_at',mi.issued_at,'reason',mi.reason) data
 FROM public.material_issue_lines line JOIN public.material_issues mi ON mi.id=line.material_issue_id JOIN public.tailor_assignments a ON a.id=mi.tailor_assignment_id JOIN public.tailoring_factories f ON f.id=a.factory_id LEFT JOIN public.tailoring_sections s ON s.id=a.section_id JOIN public.tailors t ON t.id=a.tailor_id JOIN public.locations loc ON loc.id=mi.source_location_id LEFT JOIN public.production_jobs pj ON pj.id=mi.production_job_id LEFT JOIN public.customer_tailoring_jobs cj ON cj.id=mi.customer_tailoring_job_id LEFT JOIN public.fabric_stock fs ON fs.id=line.fabric_stock_id LEFT JOIN public.fabrics fabric ON fabric.id=fs.fabric_id LEFT JOIN public.materials material ON material.id=line.material_id
 $q$;
 WHEN 'production_jobs' THEN source_sql:=$q$ SELECT j.id::text row_key,j.created_at event_at,to_jsonb(j)||jsonb_build_object('product',p.name,'design',d.name,'factory',f.name,'section',s.name,'tailor',t.real_name,'received_pieces',(SELECT count(*) FROM public.finished_products WHERE production_job_id=j.id),'latest_cost_version_id',(SELECT id FROM public.production_cost_versions WHERE production_job_id=j.id ORDER BY revision DESC LIMIT 1)) data FROM public.production_jobs j JOIN public.products p ON p.id=j.product_id JOIN public.designs d ON d.id=j.design_id JOIN public.tailor_assignments a ON a.id=j.tailor_assignment_id JOIN public.tailoring_factories f ON f.id=a.factory_id LEFT JOIN public.tailoring_sections s ON s.id=a.section_id JOIN public.tailors t ON t.id=a.tailor_id $q$;
 WHEN 'production_costs' THEN source_sql:=$q$ SELECT v.id::text row_key,v.recorded_at event_at,to_jsonb(v)||jsonb_build_object('job',j.code,'finalized',EXISTS(SELECT 1 FROM public.production_cost_requests WHERE result_id=v.id AND payload ? 'materials'),'total_paise',(SELECT coalesce(sum(amount_paise),0)::text FROM public.production_cost_lines WHERE cost_version_id=v.id),'components',(SELECT jsonb_agg(to_jsonb(l)||jsonb_build_object('input',to_jsonb(input)) ORDER BY l.id) FROM public.production_cost_lines l LEFT JOIN public.production_cost_inputs input ON input.cost_line_id=l.id WHERE l.cost_version_id=v.id),'allocations',(SELECT jsonb_agg(to_jsonb(a) ORDER BY a.finished_product_id) FROM public.finished_product_cost_allocations a WHERE a.cost_version_id=v.id)) data FROM public.production_cost_versions v JOIN public.production_jobs j ON j.id=v.production_job_id $q$;
 WHEN 'finished_products' THEN source_sql:=$q$ SELECT p.id::text row_key,p.created_at event_at,jsonb_build_object('id',p.id,'barcode',b.code,'product',product.name,'design',d.name,'job',j.code,'piece_number',p.piece_number,'status',p.status,'location',l.name,'location_id',l.id,'quantity',CASE WHEN i.id IS NOT NULL THEN public.inventory_balance(i.id,p.current_location_id)::text END,'sp_paise',price.sp_paise::text,'production_cost_paise',(SELECT a.amount_paise::text FROM public.finished_product_cost_allocations a JOIN public.production_cost_versions v ON v.id=a.cost_version_id WHERE a.finished_product_id=p.id ORDER BY v.revision DESC LIMIT 1)) data FROM public.finished_products p JOIN public.barcodes b ON b.id=p.barcode_id JOIN public.products product ON product.id=p.product_id JOIN public.designs d ON d.id=p.design_id JOIN public.production_jobs j ON j.id=p.production_job_id JOIN public.locations l ON l.id=p.current_location_id LEFT JOIN public.inventory_items i ON i.finished_product_id=p.id LEFT JOIN LATERAL(SELECT * FROM public.finished_product_prices WHERE finished_product_id=p.id ORDER BY revision DESC LIMIT 1) price ON true $q$;
 WHEN 'transfers' THEN source_sql:=$q$ SELECT line.id::text row_key,t.posted_at event_at,to_jsonb(line)||jsonb_build_object('transfer',t.code,'status',t.status,'source',source.name,'destination',destination.name,'reason',t.reason,'actor_id',t.created_by,'posted_at',t.posted_at,'quantity',line.quantity::text) data FROM public.stock_transfer_lines line JOIN public.stock_transfers t ON t.id=line.transfer_id JOIN public.locations source ON source.id=t.source_location_id JOIN public.locations destination ON destination.id=t.destination_location_id $q$;
 WHEN 'movements' THEN source_sql:=$q$ SELECT m.id::text row_key,m.occurred_at event_at,to_jsonb(m)||jsonb_build_object('source',source.name,'destination',destination.name,'actor',p.full_name,'quantity',m.quantity::text) data FROM public.inventory_movements m LEFT JOIN public.locations source ON source.id=m.source_location_id LEFT JOIN public.locations destination ON destination.id=m.destination_location_id LEFT JOIN public.profiles p ON p.id=m.actor_id $q$;
 WHEN 'orders' THEN source_sql:=$q$
 SELECT o.id::text row_key,o.created_at event_at,to_jsonb(o)-'sale_request_payload'-'tailoring_request_payload'||jsonb_build_object('source',l.name,'final_customer_price_paise',o.final_customer_price_paise::text,'revenue_state',CASE WHEN o.status='completed' AND o.payment_confirmed_at IS NOT NULL THEN 'payment_confirmed' WHEN o.kind='customer_tailoring' THEN 'customer_tailoring_booking' ELSE 'not_payment_confirmed' END,'items',(SELECT jsonb_agg(to_jsonb(it)||jsonb_build_object('quantity',it.quantity::text,'sp_snapshot_paise',it.sp_snapshot_paise::text,'final_customer_price_paise',it.final_customer_price_paise::text,'financial_snapshot',to_jsonb(fi),'finished_sale_snapshot',to_jsonb(snapshot)) ORDER BY it.id) FROM public.order_items it LEFT JOIN public.order_item_financials fi ON fi.order_item_id=it.id LEFT JOIN public.finished_product_sale_snapshots snapshot ON snapshot.order_item_id=it.id WHERE it.order_id=o.id)) data FROM public.orders o JOIN public.locations l ON l.id=o.source_location_id
 $q$;
 WHEN 'production_history' THEN source_sql:=$q$ SELECT 'status:'||e.id::text row_key,e.recorded_at event_at,to_jsonb(e)||jsonb_build_object('kind','status','job',j.code) data FROM public.production_status_events e JOIN public.production_jobs j ON j.id=e.job_id UNION ALL SELECT 'receipt:'||p.finished_product_id::text,r.recorded_at,to_jsonb(r)-'payload'||jsonb_build_object('kind','workshop_receipt','piece_id',p.finished_product_id,'job',j.code) FROM public.finished_product_receipt_pieces p JOIN public.finished_product_receipts r ON r.request_id=p.request_id JOIN public.production_jobs j ON j.id=r.production_job_id $q$;
 WHEN 'reconciliation' THEN source_sql:=$q$ SELECT id::text row_key,created_at event_at,to_jsonb(t) data FROM public.domain_reconciliation t $q$;
 WHEN 'controls' THEN source_sql:=$q$
 SELECT 'legacy:'||id::text row_key,NULL::timestamptz event_at,to_jsonb(t)||jsonb_build_object('control','unresolved_legacy') data FROM public.domain_reconciliation t WHERE resolved_at IS NULL
 UNION ALL SELECT 'than:'||th.id::text,NULL::timestamptz,jsonb_build_object('control','unreconciled_than','id',th.id,'fabric_stock_id',th.fabric_stock_id,'status',th.status) FROM public.thaans th WHERE th.status<>'draft' AND NOT EXISTS(SELECT 1 FROM public.inventory_items WHERE thaan_id=th.id)
 UNION ALL SELECT 'piece:'||p.id::text,NULL::timestamptz,jsonb_build_object('control','finished_stock_mismatch','id',p.id,'status',p.status,'location_id',p.current_location_id) FROM public.finished_products p LEFT JOIN public.inventory_items i ON i.finished_product_id=p.id WHERE i.id IS NULL OR (p.status='available' AND (public.inventory_balance(i.id,NULL)<>1 OR public.inventory_balance(i.id,p.current_location_id)<>1)) OR (p.status<>'available' AND public.inventory_balance(i.id,NULL)<>0)
 UNION ALL SELECT 'price:'||p.id::text,NULL::timestamptz,jsonb_build_object('control','available_piece_without_sp','id',p.id,'job_id',p.production_job_id) FROM public.finished_products p WHERE status='available' AND NOT EXISTS(SELECT 1 FROM public.finished_product_prices WHERE finished_product_id=p.id)
 UNION ALL SELECT 'receipt:'||j.id::text,NULL::timestamptz,jsonb_build_object('control','completed_job_not_received','id',j.id,'code',j.code) FROM public.production_jobs j WHERE status='completed' AND NOT EXISTS(SELECT 1 FROM public.finished_product_receipts WHERE production_job_id=j.id)
 UNION ALL SELECT 'cost:'||r.production_job_id::text,NULL::timestamptz,jsonb_build_object('control','received_job_without_final_cost','id',r.production_job_id) FROM public.finished_product_receipts r WHERE NOT EXISTS(SELECT 1 FROM public.production_cost_versions v JOIN public.production_cost_requests request ON request.result_id=v.id AND request.payload ? 'materials' WHERE v.production_job_id=r.production_job_id)
 UNION ALL SELECT 'negative:'||inventory_item_id::text||':'||location_id::text,NULL::timestamptz,to_jsonb(b)||jsonb_build_object('control','negative_location_balance') FROM public.v_inventory_location_balances b WHERE quantity<0
 $q$;
 WHEN 'access' THEN source_sql:=$q$ SELECT p.id::text row_key,NULL::timestamptz event_at,to_jsonb(p)||jsonb_build_object('roles',(SELECT jsonb_agg(role_key ORDER BY role_key) FROM public.user_roles WHERE user_id=p.id),'permission_overrides',(SELECT jsonb_agg(to_jsonb(o) ORDER BY permission_key) FROM public.user_permission_overrides o WHERE user_id=p.id)) data FROM public.profiles p $q$;
 WHEN 'audit' THEN source_sql:=$q$ SELECT to_char(a.occurred_at AT TIME ZONE 'UTC','YYYYMMDDHH24MISSUS')||':erp:'||a.id::text row_key,a.occurred_at event_at,to_jsonb(a)||jsonb_build_object('source','canonical','actor',p.full_name) data FROM public.erp_audit_records a LEFT JOIN public.profiles p ON p.id=a.actor_id UNION ALL SELECT to_char(created_at AT TIME ZONE 'UTC','YYYYMMDDHH24MISSUS')||':legacy:'||id::text,created_at,to_jsonb(a)||jsonb_build_object('source','legacy','previous_value',NULL,'new_value',detail) FROM public.audit_log a $q$;
 WHEN 'legacy_sales' THEN source_sql:=$q$ SELECT s.id::text row_key,s.created_at event_at,to_jsonb(s)||jsonb_build_object('source','legacy_only','items',(SELECT jsonb_agg(to_jsonb(i) ORDER BY i.id) FROM public.sale_items i WHERE i.sale_id=s.id)) data FROM public.sales s $q$;
 WHEN 'legacy_tailoring' THEN source_sql:=$q$ SELECT j.id::text row_key,j.created_at event_at,to_jsonb(j)||jsonb_build_object('source','legacy_only','lines',(SELECT jsonb_agg(to_jsonb(l) ORDER BY l.id) FROM public.tailoring_job_lines l WHERE l.job_id=j.id)) data FROM public.tailoring_jobs j $q$;
 WHEN 'legacy_movements' THEN source_sql:=$q$ SELECT m.id::text row_key,m.created_at event_at,to_jsonb(m)||jsonb_build_object('source','legacy_only') data FROM public.stock_movements m $q$;
 ELSE RAISE EXCEPTION 'Unknown Owner report dataset';
 END CASE;
 -- Stock/configuration rows without a meaningful event date are explicitly
 -- current snapshots and remain visible regardless of the transaction window.
 snapshot_dataset:=p_dataset IN('stock','fabric_stock','batches','thans','consumables','configuration','finished_products','access','controls');
 source_sql:='SELECT * FROM ('||source_sql||') report WHERE ('||snapshot_dataset::text||' OR event_at IS NULL OR (($1 IS NULL OR event_at>=$1) AND ($2 IS NULL OR event_at<$2))) AND ($4 IS NULL OR position(lower($4) in lower(data::text))>0)';
 EXECUTE 'SELECT count(*) FROM ('||source_sql||') report' INTO total_value USING p_from,p_to,p_after,nullif(btrim(p_search),'');
 order_sql:=CASE WHEN p_dataset='audit' THEN ' DESC' ELSE ' ASC' END; cursor_operator:=CASE WHEN p_dataset='audit' THEN '<' ELSE '>' END; last_aggregate:=CASE WHEN p_dataset='audit' THEN 'min' ELSE 'max' END;
 EXECUTE 'SELECT coalesce(jsonb_agg(jsonb_build_object(''key'',row_key,''event_at'',event_at,''data'',data) ORDER BY row_key'||order_sql||'),''[]''),'||last_aggregate||'(row_key) FROM (SELECT * FROM ('||source_sql||') filtered WHERE ($3 IS NULL OR row_key'||cursor_operator||'$3) ORDER BY row_key'||order_sql||' LIMIT $5) page' INTO rows_value,last_key USING p_from,p_to,p_after,nullif(btrim(p_search),''),p_limit;
 RETURN jsonb_build_object('dataset',p_dataset,'rows',rows_value,'total_rows',total_value::text,'next_cursor',CASE WHEN jsonb_array_length(rows_value)=p_limit THEN last_key END,'from',p_from,'to_exclusive',p_to,'stock_basis','current_canonical_ledger','date_basis',CASE WHEN snapshot_dataset THEN 'current_snapshot' ELSE 'event_range' END);
END; $$;

CREATE FUNCTION public.owner_erp_overview(p_from timestamptz DEFAULT NULL,p_to timestamptz DEFAULT NULL) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
BEGIN
 IF NOT public.has_role(auth.uid(),'owner') THEN RAISE EXCEPTION 'Owner required'; END IF;
 IF p_from IS NOT NULL AND p_to IS NOT NULL AND p_from>=p_to THEN RAISE EXCEPTION 'Valid half-open date range required'; END IF;
 RETURN jsonb_build_object('stock_basis','current_canonical_ledger','stock',(SELECT coalesce(jsonb_agg(to_jsonb(x) ORDER BY location_id,unit),'[]') FROM(SELECT l.id location_id,l.name location,l.kind,l.parent_id,i.unit,sum(b.quantity)::text quantity FROM public.v_inventory_location_balances b JOIN public.inventory_items i ON i.id=b.inventory_item_id JOIN public.locations l ON l.id=b.location_id GROUP BY l.id,i.unit) x),
 'paid_sales',(SELECT coalesce(jsonb_agg(to_jsonb(x) ORDER BY kind),'[]') FROM(SELECT kind,count(*)::text orders,sum(final_customer_price_paise)::text total_paise FROM public.orders WHERE status='completed' AND payment_confirmed_at IS NOT NULL AND kind IN('direct_fabric_sale','finished_product_sale') AND (p_from IS NULL OR completed_at>=p_from) AND (p_to IS NULL OR completed_at<p_to) GROUP BY kind) x),
 'customer_tailoring_bookings',(SELECT jsonb_build_object('orders',count(*)::text,'booked_customer_price_paise',coalesce(sum(final_customer_price_paise),0)::text) FROM public.orders WHERE kind='customer_tailoring' AND status='completed' AND (p_from IS NULL OR created_at>=p_from) AND (p_to IS NULL OR created_at<p_to)),
 'controls',jsonb_build_object('unresolved_legacy',(SELECT count(*) FROM public.domain_reconciliation WHERE resolved_at IS NULL),'unreconciled_thans',(SELECT count(*) FROM public.thaans th WHERE th.status<>'draft' AND NOT EXISTS(SELECT 1 FROM public.inventory_items WHERE thaan_id=th.id)),'negative_location_balances',(SELECT count(*) FROM public.v_inventory_location_balances WHERE quantity<0),'finished_stock_mismatches',(SELECT count(*) FROM public.finished_products p LEFT JOIN public.inventory_items i ON i.finished_product_id=p.id WHERE i.id IS NULL OR (p.status='available' AND (public.inventory_balance(i.id,NULL)<>1 OR public.inventory_balance(i.id,p.current_location_id)<>1)) OR (p.status<>'available' AND public.inventory_balance(i.id,NULL)<>0)),'available_pieces_without_sp',(SELECT count(*) FROM public.finished_products p WHERE status='available' AND NOT EXISTS(SELECT 1 FROM public.finished_product_prices WHERE finished_product_id=p.id)),'completed_jobs_not_received',(SELECT count(*) FROM public.production_jobs j WHERE status='completed' AND NOT EXISTS(SELECT 1 FROM public.finished_product_receipts WHERE production_job_id=j.id)),'received_jobs_without_final_cost',(SELECT count(*) FROM public.finished_product_receipts r WHERE NOT EXISTS(SELECT 1 FROM public.production_cost_versions v JOIN public.production_cost_requests request ON request.result_id=v.id AND request.payload ? 'materials' WHERE v.production_job_id=r.production_job_id))));
END; $$;
REVOKE ALL ON FUNCTION public.owner_erp_report(text,timestamptz,timestamptz,text,integer,text),public.owner_erp_overview(timestamptz,timestamptz) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.owner_erp_report(text,timestamptz,timestamptz,text,integer,text),public.owner_erp_overview(timestamptz,timestamptz) TO authenticated;
NOTIFY pgrst,'reload schema';
COMMIT;
